### ISSUE TITLE
Compatibility with better_errors 2.5

### ISSUE THREAD

**Issue by omitter** [BetterErrors/better_errors-pry#5]
Not sure if it really doesn't work or if it's just a miss in the Gemfile. Fixing the latter should be trivial.
```  
In snapshot (Gemfile.lock):
    better_errors (= 2.5.0)

  In Gemfile:
    better_errors

    better_errors-pry was resolved to 1.0.2, which depends on
      better_errors (>= 2.3.0, ~> 2.3.0)
```

**Comment by RobinDaugherty** [comment]
Thanks for the report! I just released 1.0.3 of better_errors-pry which should fix this dependency.
